name: Osek_pi_crunch_riscv
on:
  push:
    branches:
      - '**'
  pull_request:
jobs:
  target-gcc-riscv64-unknown-elf:
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: update-tools
        run: |
          wget --no-check-certificate https://buildbot.embecosm.com/job/riscv32-gcc-ubuntu2004/169/artifact/riscv32-embecosm-gcc-ubuntu2004-20230507.tar.gz
          tar -xvzf riscv32-embecosm-gcc-ubuntu2004-20230507.tar.gz
      - name: target-riscv64-unknown-elf
        run: |
          PATH=./riscv32-embecosm-gcc-ubuntu2004-20230507/bin:$PATH
          bash ./Build.sh
          ls -la ./Output/Osek_pi_crunch_riscv.hex
